### ISSUE TITLE
Duplication of course checklist box

### ISSUE THREAD

**Issue by kritinsinghal** [theRoughCode/WatsMyMajorBeta#13]
Steps to reproduce:
1. Select your major as `Bachelors of Computer Science`.
2. Go to the Course Checklist Section.
3. The following two boxes were duplicated.
<img width="660" alt="screen shot 2018-07-25 at 2 44 08 pm" src="https://user-images.githubusercontent.com/26762838/43220950-607e0e70-9019-11e8-9822-002d839b12e3.png">

Not sure if they are supposed to be like that.

**Comment by theRoughCode** [comment]
Great catch, fixed!

**Comment by riyawalia** [comment]
Found a similar bug: two boxes are repeated
<img width="691" alt="screen shot 2018-11-12 at 3 06 15 pm" src="https://user-images.githubusercontent.com/20255248/48372435-99815500-e68c-11e8-88bb-62616160f0ad.png">

**Comment by theRoughCode** [comment]
@riyawalia is the top one for the faculty core courses and the bottom one program specific?

**Comment by riyawalia** [comment]
@theRoughCode yes! I don't think it should be shown twice but I wasn't sure if it was by design or a bug.

**Comment by theRoughCode** [comment]
@riyawalia yea it's just the way that I've chosen to represent it.  I just take the faculty core courses from the general math degree requirements and show it for all math programs.  The program specific courses are then taken from the program's page, which is why you'll sometimes see duplicates.  Both sections are independent of each other though, so courses will still be checked off even though it's duplicated!
