### ISSUE TITLE
API endpoint authentication

### ISSUE THREAD

**Issue by Azhng** [theRoughCode/WatsMyMajorBeta#27]
All backend api can be directly accessed without authentication:

`curl -X POST -d ""  http://watsmymajorbeta.herokuapp.com/users/set/courselist/<username>`  can directly clear out all `/mycourses` page.

**Comment by theRoughCode** [comment]
This was definitely an issue that I was postponing.  Now that I've "opened" it up to the first wave of users, I guess this is a better time than any to implement a layer of security.  I've fixed this in a certain commit which accomplishes 2 things:

1.  Implements a secret key that I'm storing in an env var that each request has to include in its header
2.  A JWT for each user login.  I'm still debating on whether this is needed since we already have a secret key, but I'm keeping it in for now.  Also, since this was done in Passport.js, this ties in to my future work with social auth.
